// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cooc_mat
Rcpp::List cooc_mat(const arma::umat comm, const arma::cube pvalarr);
RcppExport SEXP _fastcooc_cooc_mat(SEXP commSEXP, SEXP pvalarrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat >::type comm(commSEXP);
    Rcpp::traits::input_parameter< const arma::cube >::type pvalarr(pvalarrSEXP);
    rcpp_result_gen = Rcpp::wrap(cooc_mat(comm, pvalarr));
    return rcpp_result_gen;
END_RCPP
}
// coocvec
arma::vec coocvec(const arma::uvec veci, const arma::uvec vecj, const arma::uword ntries);
RcppExport SEXP _fastcooc_coocvec(SEXP veciSEXP, SEXP vecjSEXP, SEXP ntriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec >::type veci(veciSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type vecj(vecjSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type ntries(ntriesSEXP);
    rcpp_result_gen = Rcpp::wrap(coocvec(veci, vecj, ntries));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastcooc_cooc_mat", (DL_FUNC) &_fastcooc_cooc_mat, 2},
    {"_fastcooc_coocvec", (DL_FUNC) &_fastcooc_coocvec, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastcooc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
