# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cooc_mat <- function(comm, pvalarr) {
    .Call(`_fastcooc_cooc_mat`, comm, pvalarr)
}

coocvec <- function(veci, vecj, ntries) {
    .Call(`_fastcooc_coocvec`, veci, vecj, ntries)
}

